### ISSUE TITLE
Unable to build the WAR file

### ISSUE THREAD

**Issue by karthiks3000** [Learnosity/learnosity-sdk-java#58]
The `make quickstart-assessment` does complete successfully. 
**OS**: macOS Ventura 13.5.1 
**Chip**: Apple M1 Pro
**Java**: 
openjdk 11.0.20 2023-07-18
OpenJDK Runtime Environment Temurin-11.0.20+8 (build 11.0.20+8)
OpenJDK 64-Bit Server VM Temurin-11.0.20+8 (build 11.0.20+8, mixed mode)
**Maven**: 3.8.6 (tried with 3.8.4 as well)

Error:
`The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends git make &&     rm -rf /var/lib/apt/lists/* &&     curl https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz --output /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz &&     curl https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz.sha512 --output /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz.sha512 &&     (cat /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz.sha512; echo "  apache-maven-${MAVEN_VERSION}-bin.tar.gz") > /tmp/formatted.sha512 &&     (cd /tmp || exit; sha512sum -c formatted.sha512) && (cd /opt || exit; tar zxf /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz)' returned a non-zero code: 1
make: *** [docker-build] Error 1`

**Comment by TheRealEdDawson** [comment]
Hi there @karthiks3000, thanks very much for spending time on this solution! I'll make sure our engineers are aware of this.

**Comment by anthony-murphy-lrn** [comment]
Thanks for raising this @karthiks3000 - we have updated the Docker file and associated docs
